### ISSUE TITLE
Wrapping data with H5DataIO results in different interfaces for accessing the numerical data when round-tripping

### ISSUE THREAD

**Issue by JFPerkins** [NeurodataWithoutBorders/pynwb#636] opened 2018-10-02 18:20 UTC
## 1) Bug

When wrapping data in an H5DataIO object to support compression, the data interface when round-tripping is different. For example: when dealing with a TimeSeries, the TimeSeries for write has the actual data in TimeSeries.data.data, but the TimeSeries that is read in has the data in TimeSeries.data.

### Steps to Reproduce
```python
import os
import datetime
import numpy as np
from tempfile import gettempdir
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.form.backends.hdf5.h5_utils import H5DataIO

times = np.arange(0, 10, 0.01)
data = np.sin(times)

ts_out = TimeSeries(
    name='some_data',
    source='numpy.sin',
    data=H5DataIO(data, compression=True, compression_opts=2),
    timestamps=times,
    unit='cm/s')

nwbfile_out = NWBFile(
    source='Data source',
    session_description='test',
    identifier='some_uuid',
    session_start_time=datetime.datetime.now(),
    file_create_date=datetime.datetime.now())

nwbfile_out.add_acquisition(ts_out)

filename = os.path.join(gettempdir(), "test.nwb")

with NWBHDF5IO(filename, mode='w') as io:
    io.write(nwbfile_out)

nwbfile_in = NWBHDF5IO(filename, mode='r').read()
ts_in = nwbfile_in.get_acquisition('some_data')
assert(np.allclose(ts_in.data, ts_out.data.data)) # works, but notice the required difference for accessing data
try:
    assert(np.allclose(ts_in.data, ts_out.data)) # fails with TypeError, as ts_out.data is an HDFDataIO object that doesn't support array behavior
finally:
os.remove(filename)
```
### Environment
Please describe your environment according to the following bullet points.
Linux, Python 3.6, pynwb 0.5.1

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by oruebel** [comment] 2018-10-02 21:46
Keeping the interface before write and after read exactly the same is challenging, in particular when we need to allow different variants for data as input for write (e.g., in this case for ``.data``). I agree that in an ideal world, the interfaces for write and read would always be the same, but I'm not sure this will always be possible. E.g., on write we may have a DataChunkIterator (or data stream) that generates the data on write, so the data may not even be available yet, i.e., until after the write is complete. 

In this particular case of ``TimeSeries.data.data`` vs. ``TimeSeries.data`` I believe that in the near future all datasets returned on read will need to be wrapped in some form. I think this issue will be addressed at that point, by making sure that the interface between the wrapper classes is consistent. 

In addition, one could implement ``__getitem__`` on H5DataIO to forward array slicing operations to the ``H5DataIO.data`` object. However, doing this in a fully consistent fashion is challenging because Python lists, tuples, numpy arrays, and h5py.Dataset have all slight differences in what kind of slicing they support and if you wrap an Iterable (e.g., DataChunkIterator) then slicing may not be possible at all.

**Comment by oruebel** [comment] 2018-10-03 01:09
If the main issue is that ```assert(np.allclose(ts_in.data, ts_out.data))``` then another simple solution would be to implement ``H5DataIO.__eq__``:
```python
    def __eq__(self, other):
        if not isinstance(other, DataIO):
             return self.data == other
        else:
             # compare the H5DataIO objects
```

```H5DataIO.__eq__``` to just do ```ret

**Comment by nicain** [comment] 2018-10-03 01:26
> Keeping the interface before write and after read exactly the same is challenging

Agreed, but this is critical, basic functionality, especially for a fundamental data structure like a Timeseries. In my opinion, if I can't take data and put it into a file and get the same data back out, the API is broken.  It would be like the json module allowing you marshal a dictionary to a string, but unmarshall to a list containing a dictionary.

What is the underlying source of this problem, and what is a possible short-term solution?

**Comment by bendichter** [comment] 2018-10-03 02:39
I'm inclined to agree that data should be the same after a round trip (In
fact I made the exact same request when I found a discrepancy in UnitTimes)
however I think this requirement can be relaxed in specific situations.
Here we have a structure H5DataIO that adds important write features. This
class hold the data and instructions about how to store it e.g.
compression, iterative writing, chunking, etc. When this structure is used,
the numpy array is assigned to the property data of the data object, which
means you access it with slightly different syntax. The discrepancy occurs
because there is no H5DataIO object on read. There is no need, since the
class only holds write instructions that do not affect read.

**Comment by oruebel** [comment] 2018-10-03 02:59
1. If you only use numpy arrays to define your array data then the API on read/write is the same. 

2. Just to clarify the problem is not that the data you put in is not the same data you are getting back. The values you write are the values you get back. This is an interface issue not a data issue. What is different in this case is object representing the data. 

3. The fundamental problem is that the requirements on write are fundamentally different than the requirements on read. Let's just look at a couple of examples:

   * On write we need to allow users to create data iteratively (e.g., via DataChunkIterator). In this case the data you want to write may not even exist yet until you write it, so representing it as an array that you can slice into is simple impossible on write. On read, however, you then want to get the data back that was actually written.
   * On write we need to be able to communicate per-dataset settings to the write (e.g., to define chunking, compression, etc. options). This is what H5DataIO does here. 
   * On write users want to be able to supply their data in different forms, e.g. lists vs. ndarray. On read, however, the data should always look the same, independent of how the user originally supplied the data.
   * On write you want to use numpy arrays whereas on read you actually don't want to load the whole data in numpy but use h5py.Dataset to load the data on demand 

4. Ultimately, I don't think it is possible to keep everything always exactly the same on read and write (if only because on write you are still building the data, while on read it already exists). I.e., I agree with @bendichter that we have to relax this sometimes in order to be able to define write-specific functionality. All we can do is to strive for having things as similar as possible whenever possible. Some things that one could do to improve this are, e.g:

     * Update the H5DataIO wrapper to behave more like an ndarray (i.e., at least in the cases where the users actually has the data available in memory, once you create data iterative this won't be possible).
    * We could limit the API to only allow numpy arrays for array data as input on write and force the user to convert all their data to numpy only (i.e., remove list and tuple from the list of array_data that docval allows through)
    * One could create a custom data array implementation to rule them all (ndarray, list, Iterators, DataChunkIterator, H5DataIO etc.) but I don't think that is a good idea. 
   * In the near future, I would expect that the h5py.Dataset objects will have to be wrapped on read. At that point we can also look at keeping read/write wrappers as similar as possible (and probably even have a common base class).

**Comment by ajtritt** [comment] 2018-10-03 17:31
This issue is around getting *objects*--not data--when reading that are not identical to the objects used to write the data. Can someone explain why this feature is needed?

**Comment by nicain** [comment] 2018-10-03 17:52
OK, @JFPerkins @NileGraddis  and I just circled up about this.  My understanding now is that the DataIO wrapper base class provides an incomplete interface to the data that it wraps; it does expose its wrapped data as a property, but doesn't yet provide comparison or getitem methods to access the wrapped data in the same way. This is useful, but not required, for testing that the data assigned into the object got round-tripped into/out of the file without special-casing the code that does the comparing (like the example above).

One very simple way to get this done would be a delegation like:

```python

class DataIO():
...
    def __getattr__(self, attr):
        return getattr(self.data, attr)
```
This would pick up all the comparison ops that we could ever need, the data itself would be write-protected via being a property, and it would percolate to any wrapper derived from DataIO.

Thoughts?

**Comment by nicain** [comment] 2018-10-03 18:07
Solving @JFPerkins issue/request:

```python
import numpy as np

class Foo():

    def __init__(self, data):
        self._data = data

    @property
    def data(self):
        return self._data

    def __getattr__(self, attr):
        return getattr(self.data, attr)


F = Foo(np.array([1,2,3]))
assert np.allclose(F, np.array([1,2,3]))
```

**Comment by ajtritt** [comment] 2018-10-03 18:20
@nicain thanks for clarifying the use case. I'm okay with delegating attribute resolution down to `data`. I only ask that you include a comment to that code so we remember why we did that.

**Comment by nicain** [comment] 2018-10-03 18:24
@JFPerkins FYI I self assigned, and I will test functionality against your use case.

**Closed as completed** 2018-10-04 00:54 UTC
Labels: category: enhancement
