### ISSUE TITLE
validator erroneously passing files with extensions

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#908] opened 2019-05-02 20:40 UTC
### Steps to Reproduce
```bash
python -m pynwb.validate EC125.nwb
```
on [this file](https://drive.google.com/file/d/1Tj-beQb1_6hWalCYPXGYggCBdUFv0933/view?usp=sharing) should throw an violation because EC125.nwb contains a neurodata_type defined in the ecog NDX. It should require:

```bash
python -m pynwb.validate -p ecog.namespace.yaml  EC125.nwb
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** macOS
- **Pynwb Version:** latest

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment] 2019-05-03 22:25
https://drive.google.com/file/d/1Tj-beQb1_6hWalCYPXGYggCBdUFv0933/view?usp=sharing

**Comment by t-b** [comment] 2019-05-24 20:40
This could be solved with my changes in #944.

**Comment by t-b** [comment] 2019-09-30 15:09
@bendichter Could you retry with latest dev?

**Comment by bendichter** [comment] 2019-09-30 15:12
@t-b thanks for the nudge. I'm working on this now.

**Comment by t-b** [comment] 2019-09-30 15:16
Isn't that here the same as what I complained about in #942?

**Comment by bendichter** [comment] 2019-09-30 15:46
Looks like it

**Comment by t-b** [comment] 2019-09-30 15:48
Good, closing as duplicate of #942.

**Closed as completed by t-b** 2019-09-30 15:48 UTC
Labels: topic: HDMF
