### ISSUE TITLE
[Bug]: `hdmf>=3.5.0" missing/invalid invalid dataset identifier when reading DynamicTable outside context

### ISSUE THREAD

**Issue by tuanpham96** [NeurodataWithoutBorders/pynwb#1666] opened 2023-03-16 17:40 UTC
### What happened?

When creating then using an extension with `DynamicTable`, the output NWB file cannot be read properly and table cannot be converted with `.to_dataframe()` when using 

```python
nwbfile = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True).read()
```

But when using this

```python
with NWBHDF5IO('test.nwb', mode='r', load_namespaces=True) as io:
    nwbfile_reload = io.read()
``` 
such operation is possible.

With `hdmf-3.4.7`, both approaches are fine. But with `hdmf-3.5.0` onward, it gives this error:

```
ValueError: Invalid dataset identifier (invalid dataset identifier)
```

### Steps to Reproduce

```python
# create_extension.py file
import pynwb, hdmf
print('VERSIONS: ', {'pynwb': pynwb.__version__, 'hdmf': hdmf.__version__})

from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBDatasetSpec
from pynwb.core import NWBDataInterface

name = 'ndx-my-table'
ns_path = name + ".namespace.yaml"
ext_source = name + ".extensions.yaml"

ns_builder = NWBNamespaceBuilder(name + ' extensions', name, version='0.1.0')
ns_builder.include_type('DynamicTable', namespace='hdmf-common')
ns_builder.include_type('VectorData', namespace='hdmf-common')

my_table = NWBGroupSpec(
    default_name='my_table',
    neurodata_type_def='MyTable',
    neurodata_type_inc='DynamicTable',
    doc='A table',
    datasets=[
        NWBDatasetSpec(
            name='stim_name',
            doc='Stimulus name',
            dtype='text',
            neurodata_type_inc='VectorData',
        ),
        NWBDatasetSpec(
            name='stim_id',
            doc='Stimulus',
            dtype='int',
            neurodata_type_inc='VectorData',
        )
    ]
)

ns_builder.add_spec(ext_source, my_table)
ns_builder.export(ns_path)


# use_extension.py file
import pynwb, hdmf
print('VERSIONS: ', {'pynwb': pynwb.__version__, 'hdmf': hdmf.__version__})

import pandas as pd
import numpy as np

from datetime import datetime
from dateutil import tz

from pynwb import NWBFile, NWBHDF5IO, load_namespaces, get_class

load_namespaces('ndx-my-table.namespace.yaml')

MyTable = get_class('MyTable', 'ndx-my-table')

nwbfile = NWBFile(
    session_description='abc',
    identifier='xyz',
    session_start_time= datetime(2018, 1, 2, 3, 4, 5, tzinfo=tz.gettz("US/Pacific"))
)

my_table = MyTable(name='my_table', description='abc')
my_table.add_row(stim_name = "sound", stim_id = 1)
my_table.add_row(stim_name = "odor", stim_id = 1000)

nwbfile.add_acquisition(my_table)

print('-'*100)
print('>>>> BEFORE WRITING')
print('+ TABLE OBJECT')
print(nwbfile.acquisition['my_table'])
print('+ DATAFRAME')
print(nwbfile.acquisition['my_table'].to_dataframe())

with NWBHDF5IO('test.nwb', mode='w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test.nwb', mode='r', load_namespaces=True) as io:
    nwbfile_reload = io.read()
    print('-'*100)
    print('>>>> READING INSIDE CONTEXT')
    print('+ TABLE OBJECT')
    print(nwbfile_reload.acquisition['my_table'])
    print('+ DATAFRAME')
    print(nwbfile_reload.acquisition['my_table'].to_dataframe())
    
nwbfile_outside = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True).read()

print('-'*100)
print('>>>> READING OUTSIDE CONTEXT')
print('+ TABLE OBJECT')
print(nwbfile_outside.acquisition['my_table'])
print('+ DATAFRAME')
print(nwbfile_outside.acquisition['my_table'].to_dataframe())
```

### Traceback

```python
VERSIONS:  {'pynwb': '2.2.0', 'hdmf': '3.5.0'}

----------------------------------------------------------------------------------------------

>>>> BEFORE WRITING
+ TABLE OBJECT
my_table abc.MyTable at 0x140535665082320
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

+ DATAFRAME
   stim_name  stim_id
id                   
0      sound        1
1       odor     1000

----------------------------------------------------------------------------------------------

>>>> READING INSIDE CONTEXT
+ TABLE OBJECT
my_table abc.MyTable at 0x140534859035600
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

+ DATAFRAME
   stim_name  stim_id
id                   
0      sound        1
1       odor     1000

----------------------------------------------------------------------------------------------

>>>> READING OUTSIDE CONTEXT
+ TABLE OBJECT
my_table abc.MyTable at 0x140534859037568
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc

+ DATAFRAME
VERSIONS:  {'pynwb': '2.2.0', 'hdmf': '3.5.0'}

----------------------------------------------------------------------------------------------

>>>> BEFORE WRITING
+ TABLE OBJECT
my_table abc.MyTable at 0x140714565631952
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

+ DATAFRAME
   stim_name  stim_id
id                   
0      sound        1
1       odor     1000

----------------------------------------------------------------------------------------------

>>>> READING INSIDE CONTEXT
+ TABLE OBJECT
my_table abc.MyTable at 0x140713759585232
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

+ DATAFRAME
   stim_name  stim_id
id                   
0      sound        1
1       odor     1000

----------------------------------------------------------------------------------------------

>>>> READING OUTSIDE CONTEXT
+ TABLE OBJECT
my_table abc.MyTable at 0x140713759587200
Fields:
  colnames: ['stim_name' 'stim_id']
  columns: (
    stim_name <class 'hdmf.common.table.VectorData'>,
    stim_id <class 'hdmf.common.table.VectorData'>
  )
  description: abc
                                            <------------------ `id` atrr is supposed to be here
+ DATAFRAME
Traceback (most recent call last):
  File "data/header-test/odor-metadata/issue-with-hdmf-version/./use_extension.py", line 54, in <module>
    print(nwbfile_outside.acquisition['my_table'].to_dataframe())
  File ".venv/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File ".venv/lib/python3.10/site-packages/hdmf/common/table.py", line 1112, in to_dataframe
    sel = self.__get_selection_as_dict(arg, df=True, **kwargs)
  File ".venv/lib/python3.10/site-packages/hdmf/common/table.py", line 963, in __get_selection_as_dict
    raise ve
  File ".venv/lib/python3.10/site-packages/hdmf/common/table.py", line 940, in __get_selection_as_dict
    ret['id'] = self.id[arg]
  File ".venv/lib/python3.10/site-packages/hdmf/container.py", line 564, in __getitem__
    return self.get(args)
  File ".venv/lib/python3.10/site-packages/hdmf/container.py", line 572, in get
    return self.data[args]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".venv/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 739, in __getitem__
    if self._fast_read_ok and (new_dtype is None):
  File ".venv/lib/python3.10/site-packages/h5py/_hl/base.py", line 534, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File ".venv/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 718, in _fast_read_ok
    self._extent_type == h5s.SIMPLE
  File ".venv/lib/python3.10/site-packages/h5py/_hl/base.py", line 534, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".venv/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 607, in _extent_type
    return self.id.get_space().get_simple_extent_type()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 299, in h5py.h5d.DatasetID.get_space
ValueError: Invalid dataset identifier (invalid dataset identifier)
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.10

### Package Versions

- `pynwb-2.2.0`
- `hdmf-3.4.7` vs `hdmf-3.5.0` 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by bendichter** [comment] 2023-03-16 17:51
Thanks for the report, @tuanpham96. This is indeed not intended behavior and we will need to investigate. Is this blocking you?

**Comment by tuanpham96** [comment] 2023-03-16 17:57
@bendichter I discovered that this is not just when creating and using extension. This issue also happens for created `DynamicTable` on the fly *without* any extension.

For example: 
```python
from pynwb import NWBFile, NWBHDF5IO
from hdmf.common import DynamicTable, VectorData

nwbfile = NWBFile(
    session_description='abc',
    identifier='xyz',
    session_start_time= datetime(2018, 1, 2, 3, 4, 5, tzinfo=tz.gettz("US/Pacific"))
)

my_table =  DynamicTable(
    name='my_table', description='abc',
    columns=[
        VectorData('stim_name', 'stimulus name', ['sound', 'odor']),
        VectorData('stim_id', 'stimulus ID', [1,1000]),
    ]
)

nwbfile.add_acquisition(my_table)
```

<details><summary>Full script</summary>

```python
import pynwb, hdmf
print('VERSIONS: ', {'pynwb': pynwb.__version__, 'hdmf': hdmf.__version__})

import pandas as pd
import numpy as np

from datetime import datetime
from dateutil import tz

from pynwb import NWBFile, NWBHDF5IO
from hdmf.common import DynamicTable, VectorData

nwbfile = NWBFile(
    session_description='abc',
    identifier='xyz',
    session_start_time= datetime(2018, 1, 2, 3, 4, 5, tzinfo=tz.gettz("US/Pacific"))
)

my_table =  DynamicTable(
    name='my_table', description='abc',
    columns=[
        VectorData('stim_name', 'stimulus name', ['sound', 'odor']),
        VectorData('stim_id', 'stimulus ID', [1,1000]),
    ]
)

nwbfile.add_acquisition(my_table)

print('-'*100)
print('>>>> BEFORE WRITING')
print('+ TABLE OBJECT')
print(nwbfile.acquisition['my_table'])
print('+ DATAFRAME')
print(nwbfile.acquisition['my_table'].to_dataframe())

with NWBHDF5IO('test.nwb', mode='w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test.nwb', mode='r', load_namespaces=True) as io:
    nwbfile_reload = io.read()
    print('-'*100)
    print('>>>> READING INSIDE CONTEXT')
    print('+ TABLE OBJECT')
    print(nwbfile_reload.acquisition['my_table'])
    print('+ DATAFRAME')
    print(nwbfile_reload.acquisition['my_table'].to_dataframe())
    
nwbfile_outside = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True).read()

print('-'*100)
print('>>>> READING OUTSIDE CONTEXT')
print('+ TABLE OBJECT')
print(nwbfile_outside.acquisition['my_table'])
print('+ DATAFRAME')
print(nwbfile_outside.acquisition['my_table'].to_dataframe())
```

</details>

> Is this blocking you?

Unfortunately yes, since it affects `DynamicTable` objects inside some of the lab's data, that were not created with extension.

**Comment by oruebel** [comment] 2023-03-16 18:32
Since it works with the context manager, my guess (based on the error) is that if you change:

```nwbfile = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True).read()```

to

```
nwbio = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True)
nwbfile = nwbio.read()
```

that this should resolve the problem.

I think the problem is that when placing ``NWBHDF5IO().read()`` in a single line, the NWBHDFIO object is not being saved in a variable but only the NWBFile object that is being returned by the call to ``read()``. As such, Python will garbage collect the NWBHDF5IO object which on deletion closes the HDF5 file. PyNWB loads data lazily, i.e., it only parses the structure of an NWB file on read, but the bulk data from arrays is loaded on request. As such, the io object needs to remain open as long as you need to read data from that file and the io object should be closed or deleted once you no longer need it.

**Comment by tuanpham96** [comment] 2023-03-16 19:16
> ```python
> nwbio = NWBHDF5IO('test.nwb', mode='r', load_namespaces=True)
> nwbfile = nwbio.read()
> ```
@oruebel Awesome! That works, thank you for that and the explanation! Should I close this issue or keep it open until the next release?

**Comment by oruebel** [comment] 2023-03-16 20:09
Great, I'm glad that helped fix the problem. 

As a good practice, I would suggest adding a call to ``nwbio.close`` or explicitly deleting the object ``del nwbio`` once you are done reading from the file. If you are just running a script, this is not strictly necessary since the object will be deleted by Python when the script finishes and since you are opening the file in read-only mode, but it is good style and is useful if your code will be used by others to make sure all files are closed when they are no longer needed. 

I'll close this issue for now, but please feel free to reopen the issue or create a new one if you have any other questions.

**Closed as completed by oruebel** 2023-03-16 20:09 UTC
Labels: category: bug, priority: high

**Comment by sneakers-the-rat** [comment] 2023-09-23 07:43
Just came across this as well - +1 for this being something worth catching and giving a more informative error message.
