### ISSUE TITLE
question: external dataset reference?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#408] opened 2018-03-26 02:46 UTC
Is it possible to use pynwb to reference a dataset from another hdf5 file?

**Comment by oruebel** [comment] 2018-03-26 20:38
Just in case I'm getting some of details wrong, let me CC @ajtritt here. I believe there are two options how this can work right now:

1) If you want to link against an object with a ``neurodata_type`` that has a corresponding container class in the PyNWB API, then what you would do is to simply open the file that has that container and add the container to your new file. On write, PyNWB will then create and ExternalLink in the HDF5 file.

2) If you want just one particular dataset to be an ExternalLink, then you would right now just use the corresponding h5py.Dataset object as value for the corresponding parameter on the PyNWB container class. There are a couple of potential pitfalls with this though: 1) right now this behavior is not yet configurable, 2) handling the case where there is a mismatch between attributes for the dataset are I believe not handled. For (1) the solution is to update H5DataIO wrapper to configure the behavior and to update the HDF5IO accordingly. I have an open pull request https://github.com/NeurodataWithoutBorders/pynwb/pull/400 where I've updated H5DataIO and it would make sense to add it there. For 2) I think the solution will likely be appropriate Error and/or warning messages as having conflicting attributes on a dataset is likely not going to work. 

Fixing some of these issues and documenting them is part of my plan for the Advanced I/O tutorial for the hackathon. 

As crude example, in code cell 16 in the following notebook https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/notebooks/convert-crcns-ret-1-meisterlab.ipynb
I'm did the following:

```
# Open the custom HDF5 file with the stimulus data to get the stimulus dataset
stim_data_file = h5py.File(curr_stimulus['data'][0], 'r')
stim_ext_data = stim_data_file[curr_stimulus['data'][1]]
# By assigning the existing HDF5 dataset from the external file, PyNWB automatically creates an ExternalLink for data`
img = ImageSeries(data=stim_ext_data, ....)```

Doing this though h5py is really not the right way of doing this. At least in this case, you can (and should) do this all via PyNWB. The problem is that I wrote this notebook a while ago and it need to be updated.

**Comment by oruebel** [comment] 2018-03-26 20:39
@bendichter is it Ok to close this issue for now and I'll add this to the work plan for Advanced I/O for the hackathon.

**Comment by bendichter** [comment] 2018-03-26 22:00
Thanks Oliver, that example is very helpful! Is there test coverage for this?

**Comment by oruebel** [comment] 2018-03-26 22:42
As far as I can tell those lines in the HDF5IO backend are not yet covered.

**Comment by oruebel** [comment] 2018-03-30 02:32
I've updated  #400 to now allow 1) setting the default behavior for whether h5py.Dataset are copied or linked to on write and 2) allow customization of this behavior via H5DataIO on a per-dataset basis. I've also added some tests to cover this behavior.

**Closed as completed by oruebel** 2018-03-30 02:32 UTC

**Comment by bendichter** [comment] 2018-03-30 02:35
great, thanks for working on that! I'll test it out tomorrow.
