### ISSUE TITLE
H5DataIO input arg type changes behavior of interface

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#807] opened 2019-01-30 19:42 UTC
## 1) Bug

Related issue: https://github.com/NeurodataWithoutBorders/pynwb/issues/636
Cross-reference: https://github.com/AllenInstitute/AllenSDK/issues/342

### Steps to Reproduce
```python
from tempfile import gettempdir
import os
import datetime
from dateutil.tz import tzlocal
import numpy as np

from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.form.backends.hdf5.h5_utils import H5DataIO


filename = os.path.join(gettempdir(), "test.nwb")

test_speed = [10., 20.]

ts1 = TimeSeries(name='ts1',
                 data=H5DataIO(np.array(test_speed)),
                 timestamps=H5DataIO(test_speed),
                 unit='cm/s')

ts2 = TimeSeries(name='ts2',
                 data=H5DataIO(test_speed),
                 timestamps=H5DataIO(test_speed),
                 unit='cm/s')

filename = os.path.join("./test.nwb")

nwbfile = NWBFile(
    session_description='test foraging2',
    identifier='behavior_session_uuid',
    session_start_time=datetime.datetime.now(tzlocal()),
    file_create_date=datetime.datetime.now(tzlocal()))

nwbfile.add_acquisition(ts1)
nwbfile.add_acquisition(ts2)


with NWBHDF5IO(filename, 'w') as nwb_file_writer:
    nwb_file_writer.write(nwbfile)

with NWBHDF5IO(filename, 'r') as nwb_file_reader:
    obtained = nwb_file_reader.read()

    assert(np.allclose(nwbfile.acquisition['ts1'].data, obtained.acquisition['ts1'].data)) # Works
    assert(np.allclose(nwbfile.acquisition['ts2'].data, obtained.acquisition['ts2'].data)) # Breaks
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda or Python
- **Python Version:** Python 2.7 or Python 3.6
- **Operating System:** Windows, macOS or Linux
- **Pynwb Version:** Version of Pynwb used

### Problem/Use Case
Need consistent interface for input

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment] 2019-01-31 02:52
@nicain  thanks for the script. I have not fixed the issue yet, but here some additional details from my first look at this. 

The short version is, the problem appears to be that ``np.isfinite`` fails on an ``H5DataIO`` object that wraps a list but succeeds on an ``H5DataIO`` object that wraps a numpy array. The slightly longer version is:

1. The problem is that the call to ``np.allclose(...)`` breaks (i.e., the script also fails without the ``assert`` around the ``np.allclose``).
2. In both cases the ``np.allclose`` tries to compare an ``H5DataIO`` object with an ``h5py.Dataset``. However, when the ``H5DataIO`` wraps a numpy array the call succeeds and when wrapping a list it does not. 
3. When changing the call to get the data from ``H5DataIO`` the call to ``np.allclose`` succeeds, i.e., the following works:

```
np.allclose(nwbfile.acquisition['ts1'].data.data, obtained.acquisition['ts1'].data)
np.allclose(nwbfile.acquisition['ts2'].data.data, obtained.acquisition['ts2'].data)
```

4. The error that is being generated indicates that the problem is actually with ``numpy.isfinite`` not working:

```
...
  File "...site-packages/numpy/core/numeric.py", line 2256, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "...site-packages/numpy/core/numeric.py", line 2332, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

To confirm this we can try to call ``np.isfinite`` directly on the 4 relevant objects:

```
    print(np.isfinite(nwbfile.acquisition['ts1'].data), nwbfile.acquisition['ts1'].data)   # Works
    print(np.isfinite(obtained.acquisition['ts1'].data), obtained.acquisition['ts1'].data) # Works
    print(np.isfinite(obtained.acquisition['ts2'].data), obtained.acquisition['ts2'].data) # Works
    print(np.isfinite(nwbfile.acquisition['ts2'].data), nwbfile.acquisition['ts2'].data) # Breaks
```
which results in:

```
[ True  True] <pynwb.form.backends.hdf5.h5_utils.H5DataIO object at 0x104983898>
[ True  True] <HDF5 dataset "data": shape (2,), type "<f8">
[ True  True] <HDF5 dataset "data": shape (2,), type "<f8">
Traceback (most recent call last):
  File "test_h5iobug.py", line 49, in <module>
    print(np.isfinite(nwbfile.acquisition['ts2'].data), nwbfile.acquisition['ts2'].data) # Breaks
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by oruebel** [comment] 2019-01-31 03:21
I think what is happening is the following:

1. ``DataIO`` is delegating via  the  [def __getattr__(self, attr)](https://github.com/NeurodataWithoutBorders/pynwb/blob/605d78d93f84328be54c6a09b301f86de3631658/src/pynwb/form/data_utils.py#L480) function the attributes from the data object it is wrapping. 
2. A numpy array provides additional functions/attributes that the standard python list does not have.
3. Because ``DataIO`` delegates the attributes, this allows numpy to cast the H5DataIO object to a numpy array when the wrapped object is a numpy array but fails when the wrapped object is a list. 

I am not exactly sure yet, what function we need to add to allow numpy to cast the H5DataIO object to a numpy array, but it looks like that is the missing piece here.

**Comment by oruebel** [comment] 2019-01-31 04:00
Ok, one possible fix for this seems to be to update ``DataIO`` and define the ``__array__`` function. I added the following to ``DataIO`` and it seems to work:

```
    def __array__(self):
        """
        Support conversion of DataIO.data to a numpy array. This function is
        provided to improve transparent interoperability of DataIO with numpy.

        :return: An array instance of self.data
        """
        if hasattr(self.data, '__array__'):
            return self.data.__array__()
        elif isinstance(self.data, DataChunkIterator):
            raise NotImplementedError("Conversion of DataChunkIterator to array not supported")
        else:
            # NOTE this may result in a copy of the array
            return np.asarray(self.data)
```

Basically all the function does is that it calls ``DataIO.data.__array__()`` if possible (i.e., it delegates first) and if that does not work it converts ``DataIO.data`` to a numpy array and returns that instead. 

@ajtritt

**Comment by oruebel** [comment] 2019-01-31 18:07
I have committed the fix on https://github.com/hdmf-dev/hdmf/pull/1 . This will come into PyNWB when the move of ``pynwb.form`` to ``hdmf`` is done. @nicain  if this is critical then in the meantime you can just add the ``__array`` function from my last comment to pynwb.form.data_utils.DataIO on your local install and once the refactoring is done it will be in PyNWB proper.

**Closed as completed by oruebel** 2019-01-31 18:07 UTC
Labels: category: bug
