### ISSUE TITLE
Cannot round-trip TimeSeries with empty timestamps

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#881] opened 2019-04-11 22:15 UTC
```
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.behavior import BehavioralTimeSeries, BehavioralEvents
from pynwb import ProcessingModule
import numpy as np
import datetime

filename = "./debug.nwb"

nwbfile_out = NWBFile(
    session_description='test foraging2',
    identifier='behavior_session_uuid',
    session_start_time=datetime.datetime.now(),
    file_create_date=datetime.datetime.now(),
)

ts1 = TimeSeries(
    name='1',
    timestamps=[],
    unit='s'
)

# Add lick event timeseries to lick interface:
licks_interface = BehavioralEvents([ts1], 'licks')

# Add lick interface to nwb file, by way of a processing module:
licks_mod = ProcessingModule('licking', 'Licking behavior processing module')
licks_mod.add_data_interface(licks_interface)
nwbfile_out.add_processing_module(licks_mod)

with NWBHDF5IO(filename, mode='w') as io:
    io.write(nwbfile_out)

# Fails here:
nwbfile_in = NWBHDF5IO(filename, mode='r').read()
```

**Comment by nicain** [comment] 2019-04-12 23:27
Can anyone suggest a a work-around for this problem?

**Comment by bendichter** [comment] 2019-04-12 23:30
Timestamps are a required field so this is going to be tough. You could use
a np.nan to mark it as null but I know that's not ideal

**Comment by ajtritt** [comment] 2019-04-15 17:02
Why are you trying to write empty timestamps?

**Comment by nicain** [comment] 2019-04-16 19:20
For example, we record the licking events in a timeseries in  BehavioralEvents interface.  Sometimes, an animal doesn't lick, but that doesn't mean that we didn't record that signal; if I cannot add an empty timeseries, I cannot differentiate between "we looked for lick events, but didn't see any" and "we did not look for lick events".

**Comment by ajtritt** [comment] 2019-04-17 14:44
Gotcha, that makes sense. I suspect the issue is that empty datasets don't get written. I just encountered this problem myself, and I'm in the middle of tracking it down.

**Comment by t-b** [comment] 2020-01-29 12:38
@nicain Can you verify if this is fixed by https://github.com/hdmf-dev/hdmf/pull/107? If not please reopen.

**Closed as completed by t-b** 2020-01-29 12:38 UTC
Labels: category: bug
