### ISSUE TITLE
NWB website improperly served from https

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#244] opened 2017-11-11 13:18 UTC
### Steps to Reproduce

Go to https://www.nwb.org/ 

Here is a screenshot:

![https-nwb-broken](https://user-images.githubusercontent.com/219043/32689799-ed200764-c6b8-11e7-9dc0-a2190dd8cfe9.png)

Cc: @oruebel

**Comment by cmartin-kavlifoundation** [comment] 2017-11-11 15:21
I get the same issue when going to https://www.nwb.org but _not_ if I go to https://live-nwb.pantheonsite.io/ which is the direct link to the web hosting site.  So there is something weird going on with https.  This may take a bit of sleuthing to track down.  I'm distracted by another event at SfN at the moment, so I'm going to have to defer working this until later in the afternoon.  In the interim if someone spots an obvious fix, let me know.

**Comment by mgrauer** [comment] 2017-11-11 15:44
The issue is that the sites are https, but some of the nwb.org resources are being requested as http, resulting in browser console errors like

>Mixed Content: The page at 'https://www.nwb.org/' was loaded over HTTPS, but requested an insecure script 'http://www.nwb.org/wp-content/themes/Total/assets/js/wpex.min.js?ver=4.4.1'. This request has been blocked; the content must be served over HTTPS.

Looking at a link for the same resource across the two sites in the page, nwb.org is requesting http but pantheonsite is requesting https:

    https://live-nwb.pantheonsite.io/wp-content/themes/Total/assets/js/wpex.min.js?ver=4.4.1
    http://www.nwb.org/wp-content/themes/Total/assets/js/wpex.min.js?ver=4.4.1

I don't know how these pages are constructed, but if all of the links on nwb.org are changed to https, it should resolve the issue.

**Comment by cmartin-kavlifoundation** [comment] 2017-11-11 16:31
I just made some changes to the DNS entry for nwb.org that seemed to have solved the problem with https.  It may take a few hours for the new DNS details to propagate, but once they have I will check again and close this ticket.  If you still see problems let me know.

**Comment by jcfr** [comment] 2017-11-11 16:36
I confirm that the layout is now correct using: https://nwb.org  👍 

But there is still the issue of mixed content that @mgrauer described above.

![nwb-mixed-content](https://user-images.githubusercontent.com/219043/32691371-9d54b448-c6d4-11e7-94d0-2cdaf68e5f94.png)

**Comment by cmartin-kavlifoundation** [comment] 2017-11-11 16:38
Thanks for the confirmation, now that the urgent piece is fixed (the formatting with https), I'll address the secondary issue of the mixed http and https content.

**Comment by mgrauer** [comment] 2017-11-11 16:39
The website works for me now.

Almost all the resources are now being served via https, there is one remaining http resource, though the browser is issuing a warning rather than an error and allowing this image through for me.

    http://live-nwb.pantheon.io/wp-content/uploads/2015/08/brain.png

**Comment by jcfr** [comment] 2017-11-11 16:43
To put things in context and clearly indicate where in the source code to update:

![brain-png-source](https://user-images.githubusercontent.com/219043/32691426-5910e54e-c6d5-11e7-9082-d1e761e542e0.png)

![brain-mng-downloaded-from-http](https://user-images.githubusercontent.com/219043/32691425-58f64e3c-c6d5-11e7-9a13-c3e4fbb8532d.png)

**Comment by cmartin-kavlifoundation** [comment] 2017-11-11 17:00
Fixed, this was an old link that had snuck in somehow.  https now gives me no warnings and the page is rendering properly, so I'm going to mark this closed later this afternoon.  
Prophylatically, I'm looking through the lower level pages to make sure they don't have any http: images that have snuck through and cause https warnings.  Please feel free to comment if you spot anything else.

**Comment by jcfr** [comment] 2017-11-11 17:12
Thanks 👍 

These pages have mixed content:

* https://www.nwb.org/2015/11/20/identifying-the-brains-essential-elements/
  * Easy to fix - served from nwb.org

![http-1](https://user-images.githubusercontent.com/219043/32691681-5fb9234e-c6d9-11e7-9153-1190753e2922.png)


* https://www.nwb.org/2014/09/07/feature-breaking-down-the-data-barriers-in-neuroscience/

  * corresponding https url is now working

![http-2](https://user-images.githubusercontent.com/219043/32691683-6e6365d0-c6d9-11e7-9092-cd434e677913.png)

  * Proposed Solutions:
    * upload assets onto nwb.org (may be trough the blogging platform ? )

**Comment by cmartin-kavlifoundation** [comment] 2017-11-12 00:43
All of the https issues with formatting and mixed content have been cleaned up, closing ticket.

**Closed as completed by cmartin-kavlifoundation** 2017-11-12 00:43 UTC

**Comment by jcfr** [comment] 2017-11-12 00:44
Thanks @cmartin-kavlifoundation
