### ISSUE TITLE
Cannot reload example with epochs using io module.

### ISSUE THREAD

**Issue by AdamRTomkins** [NeurodataWithoutBorders/pynwb#393] opened 2018-03-14 16:01 UTC
## Cannot reload example with epochs

When following the Shire Example, I am unable to reload the NWB file when epochs are included. The following Error is encountered:

```
Exception: Could not construct Epoch object
    incorrect type for 'tags' (got 'H5Dataset', expected 'tuple or list'): Epoch (epoch1)
```

In this case the H5 file stores the epochs, but only the description and epoch name is recorded to file, and not the start and stop times. 

### Steps to Reproduce
```
# Failing Example

from datetime import datetime
from pynwb import NWBFile

f = NWBFile('the PyNWB tutorial', 'my first synthetic recording', 'EXAMPLE_ID', datetime.now(),
            experimenter='Dr. Bilbo Baggins',
            lab='Bag End Laboratory',
            institution='University of Middle Earth at the Shire',
            experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
            session_id='LONELYMTN')

epoch_tags = ('example_epoch',)

ep1 = f.create_epoch(source='an hypothetical source', name='epoch1', start=0.0, stop=1.0,
                     tags=epoch_tags,
                     description="the first test epoch")

from pynwb import get_manager
from pynwb.form.backends.hdf5 import HDF5IO

filename = "example.h5"
io = HDF5IO(filename, manager=get_manager(), mode='w')
io.write(f)
io.close()

io = HDF5IO(filename, manager=get_manager(), mode='r')
f = io.read()

```

### Environment

- **Python Executable:** Python 
- **Python Version:** Python 2.7
- **Operating System:**  Ubuntu 14.04 
- **Pynwb Version:** Pynwb 0.2.0.post.dev416

**Comment by bendichter** [comment] 2018-03-14 17:17
Thanks for the report, Adam. It appears that some recent changes to the data structure caused issues for epoch builders. We're looking into a fix. In the meantime, would it be possible for you to hold off on using Epochs?

duplicate of #389

**Comment by bendichter** [comment] 2018-03-23 21:20
I think the best way to prevent this type of error in the future is to add `io.read()` statements in the demo code outside the blocks included in the documentation. @ajtritt what do you think?

**Comment by ajtritt** [comment] 2018-03-23 23:10
@bendichter  [already on it](https://github.com/NeurodataWithoutBorders/pynwb/blob/enh/sphinx_gallery/docs/gallery/examples/file.py) :) 

@AdamRTomkins I had to do some refactoring of how epochs get stored. You will still use the `create_epoch` method, but it's change a little bit. See the documentation for details.

**Comment by ajtritt** [comment] 2018-05-24 20:57
@AdamRTomkins `create_epoch` has changed. Please update your code to use the new method and let me know if you run into the same problem.

**Closed as completed** 2018-05-24 20:56 UTC
